In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
import seaborn as sns
from sklearn.decomposition import PCA as sklearnPCA
from sklearn.manifold import TSNE

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
# df = pd.read_csv("teste.csv", index_col=0)

In [2]:
# df[df['ID Aluno']==208149] #id
import warnings
warnings.filterwarnings('ignore')

In [3]:
from plotly.offline import init_notebook_mode, iplot
import plotly.offline as py
import plotly.graph_objs as go
init_notebook_mode(connected=True)

# preparing data

In [4]:
primeiroCiC = ['116301', '118001', '118010', '113034', '140481', '145971']
segundoCiC = ['116319', '115045', '118028', '118036', '113042']
terceiroCiC = ['118044', '118052', '113956', '113051', '117366']


primeiroLic1 =['116793', '117366', '145971', '147389', '194221']
segundoLic1 = ['113034', '116301', '125156']
terceiroLic1 = ['115045', '116319', '125172']

primeiroLic2 =['113492', '194221', '113450', '113476']
segundoLic2 = ['113034', '116319', '191027', '150649', '194280']
terceiroLic2 = ['115045', '113093', '117366', '117889']

primeiroEngComp =['113034', '113093', '113476', '117528', '118001', '118010']
segundoEngComp = ['118028', '118036', '113042', '115045', '116319']
terceiroEngComp =['113051', '117242', '170054', '201600', '206075']


primeiroMec = ['114626', '114634', '118010', '113476', '113034', '118001', '168891']
segundoMec = ['168891', '113093', '118028', '118036', '115045', '168874']
terceiroMec = ['113051', '118044', '118052', '168769', '116319']

primeiroRedes = ['113034', '113093', '118001', '118010', '167959']
segundoRedes = ['113042', '115045', '118028', '118036', '169676']
terceiroRedes = ['113051', '113301', '167983', '169749']


undropableCol = ["curso","saiu","Cotista","Raça","Sexo","Tipo de Escola"]#, 'Ingresso_unb'

In [5]:
df0 = pd.read_csv("aluno_quant_Materias_Media_nao_cotistas_0.csv", index_col=0)
df1 = pd.read_csv("aluno_quant_Materias_Media_nao_cotistas_1.csv", index_col=0)
df2 = pd.read_csv("aluno_quant_Materias_Media_nao_cotistas_2.csv", index_col=0)
df3 = pd.read_csv("aluno_quant_Materias_Media_nao_cotistas_3.csv", index_col=0)
df4 = pd.read_csv("aluno_quant_Materias_Media_nao_cotistas_4.csv", index_col=0)
df5 = pd.read_csv("aluno_quant_Materias_Media_nao_cotistas_5.csv", index_col=0)

In [6]:
dfComp = df0[undropableCol+primeiroLic1+segundoLic1+terceiroLic1].fillna(-1)
dfRedes = df1[undropableCol+primeiroRedes+segundoRedes+terceiroRedes].fillna(-1)
dfCic = df2[undropableCol+primeiroCiC+segundoCiC+terceiroCiC].fillna(-1) 
dfMec = df3[undropableCol+primeiroMec+segundoMec+terceiroMec].fillna(-1) 
dfEng = df4[undropableCol+primeiroEngComp+segundoEngComp+terceiroEngComp].fillna(-1) 

# PCA

In [7]:
def get_cmap(n, name='hsv'):
    '''Returns a function that maps each index in 0, 1, ..., n-1 to a distinct 
    RGB color; the keyword argument name must be a standard mpl colormap name.'''
    return plt.cm.get_cmap(name, n)

In [8]:
def PCA (df, currentLabel = 'saiu'):
    data = (
        df

    )
    
    x = data.iloc[:].values
    y = data[currentLabel].values

    data[currentLabel]
    numColors = len(data[currentLabel].unique())

    sklearn_pca = sklearnPCA(n_components=2)

    Y_sklearn = sklearn_pca.fit_transform(x)

    cmap = get_cmap(numColors+1)
    colorList = [cmap(i) for i in range(1, numColors+1)]


    with plt.style.context('seaborn-whitegrid'):
        plt.figure(figsize=(15, 10))
        for lab, col in zip(data[currentLabel].unique(),
                            colorList):
            plt.scatter(Y_sklearn[y==lab, 0],
                        Y_sklearn[y==lab, 1],
                        label=lab,
                        c=col)
        plt.xlabel('Principal Component 1')
        plt.ylabel('Principal Component 2')
        plt.legend(loc='lower right')
        plt.tight_layout()
        plt.show()

    plt.show()

# TSNE

In [9]:
def formatColor(color):
    return 'rgb('+str(int(color[0]*255))+','+str(int(color[1]*255))+','+str(int(color[2]*255))+')'

    
def tsne(df, currentLabel = 'saiu'):
    a = df
    X = a.values
    X_embedded = TSNE(n_components=2).fit_transform(X)
    
    
    data = a
    Y_sklearn = X_embedded
    y = data[currentLabel].values
    numColors = len(data[currentLabel].unique())

    cmap = get_cmap(numColors+1)
    colorList = [cmap(i) for i in range(1, numColors+1)]


    traceArr = []
    for lab, col in zip(data[currentLabel].unique(),
                        colorList):
        
        trace1 = go.Scatter(
            x=Y_sklearn[y==lab, 0],
            y=Y_sklearn[y==lab, 1],
#             z=Y_sklearn[y==lab, 2],
            mode='markers',
            name = str(lab),
            marker=dict(
                size=5,
                color=formatColor(col),
                opacity=0.8
            )
        )
        traceArr.append(trace1)

    data = traceArr
    layout = go.Layout(
        margin=dict(
            l=0,
            r=0,
            b=0,
            t=0
        )
    )
    fig = go.Figure(data=data, layout=layout)
    py.iplot(fig, filename='3d-scatter-colorscale')

In [10]:
# draw2dFrame(a, X_embedded, 'saiu')

# knn

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.model_selection import StratifiedKFold

In [12]:
# a = a[a["saiu"]!=0]
# y = a["saiu"]
# X = a.drop(["saiu"], axis = 1)

In [13]:

def knn (df, currentLabel = 'saiu'):
    a = df[df[currentLabel]!=0]
    y = a[currentLabel]
    X = a.drop([currentLabel], axis=1)
    
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    scaler = StandardScaler()  
    scaler.fit(X_train)

    X_train = scaler.transform(X_train)  
    X_test = scaler.transform(X_test)  
    
    classifier = KNeighborsClassifier(n_neighbors=2)  
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    
    print(confusion_matrix(y_test, y_pred))  
    print(classification_report(y_test, y_pred))
    
def knncv (df, currentLabel = 'saiu'):
    a = df[df[currentLabel]!=0]
    y = a[currentLabel]
    X = a.drop([currentLabel], axis=1)
    X = X.values
    y = y.values
    skf = StratifiedKFold(n_splits=5)
#     print(skf.split(X, y))
    array = []
    for train, test in skf.split(X, y):
#         X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
        X_train = X[train]
        X_test = X[test]
        y_train = y[train]
        y_test = y[test]
        scaler = StandardScaler()  
        scaler.fit(X_train)

        X_train = scaler.transform(X_train)  
        X_test = scaler.transform(X_test)  

        classifier = KNeighborsClassifier(n_neighbors=2)  
        classifier.fit(X_train, y_train)
        y_pred = classifier.predict(X_test)

        print(confusion_matrix(y_test, y_pred))  
        print(classification_report(y_test, y_pred))
        array.append(classification_report(y_test, y_pred, output_dict = True))
#         print(X[train])
    print(array[1]['-1']['precision'])
    


In [14]:
knncv(dfCic)

[[137  13]
 [ 61  99]]
              precision    recall  f1-score   support

          -1       0.69      0.91      0.79       150
           1       0.88      0.62      0.73       160

   micro avg       0.76      0.76      0.76       310
   macro avg       0.79      0.77      0.76       310
weighted avg       0.79      0.76      0.76       310

[[135  15]
 [ 26 134]]
              precision    recall  f1-score   support

          -1       0.84      0.90      0.87       150
           1       0.90      0.84      0.87       160

   micro avg       0.87      0.87      0.87       310
   macro avg       0.87      0.87      0.87       310
weighted avg       0.87      0.87      0.87       310

[[146   4]
 [ 38 122]]
              precision    recall  f1-score   support

          -1       0.79      0.97      0.87       150
           1       0.97      0.76      0.85       160

   micro avg       0.86      0.86      0.86       310
   macro avg       0.88      0.87      0.86       310
weigh

In [15]:
# scaler = StandardScaler()  
# scaler.fit(X_train)

# X_train = scaler.transform(X_train)  
# X_test = scaler.transform(X_test)  

In [16]:
# classifier = KNeighborsClassifier(n_neighbors=2)  
# classifier.fit(X_train, y_train)
# y_pred = classifier.predict(X_test)  

In [17]:
 
# print(confusion_matrix(y_test, y_pred))  
# print(classification_report(y_test, y_pred))
# knn(X, y)

In [18]:
# a

# correlação heatmap

In [19]:
def corrMat(df):
    f = (df).corr('spearman')
    plt.figure(figsize=(16, 6))
    sns.heatmap(f, annot=True)


# gradient boosting

In [46]:
from sklearn import ensemble

def gradent(df, currentLabel = 'saiu'):
    params = {
        'n_estimators': 150,
        'max_depth': 6,
        'learning_rate': 0.1,
        'criterion': 'friedman_mse'
    }
    
    a = df[df[currentLabel]!=0]
    y = a[currentLabel]
    X = a.drop([currentLabel], axis=1)
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    
    gradient_boosting_regressor = ensemble.GradientBoostingRegressor(**params)

    gradient_boosting_regressor.fit(X_train, y_train)
    
    y_pred = gradient_boosting_regressor.predict(X_test)
    y_pred = (y_pred>0)*1
    y_pred = np.array([x if x !=0 else -1 for x in y_pred])
#     print (y_pred)
    print(confusion_matrix(y_test, y_pred))  
    print(classification_report(y_test, y_pred))
    
def gradentcv(df, currentLabel = 'saiu'):
    params = {
        'n_estimators': 150,
        'max_depth': 6,
        'learning_rate': 0.1,
        'criterion': 'friedman_mse'
    }
    
    a = df[df[currentLabel]!=0]
    y = a[currentLabel]
    X = a.drop([currentLabel], axis=1)
    X = X.values
    y = y.values
    skf = StratifiedKFold(n_splits=5)
    
    
    array = []
    for train, test in skf.split(X, y):
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
        X_train = X[train]
        X_test = X[test]
        y_train = y[train]
        y_test = y[test]
        
#         scaler = StandardScaler()  
#         scaler.fit(X_train)

#         X_train = scaler.transform(X_train)  
#         X_test = scaler.transform(X_test)  

        
        gradient_boosting_regressor = ensemble.GradientBoostingRegressor(**params)

        gradient_boosting_regressor.fit(X_train, y_train)

        y_pred = gradient_boosting_regressor.predict(X_test)
        y_pred = (y_pred>0)*1
        y_pred = np.array([x if x !=0 else -1 for x in y_pred])
    #     print (y_pred)
        print(confusion_matrix(y_test, y_pred))  
        print(classification_report(y_test, y_pred))
        array.append(classification_report(y_test, y_pred, output_dict = True))
#         print(X[train])
    print(array[1]['-1']['precision'])

In [44]:
gradent(dfComp)

[[ 47  13]
 [ 23 109]]
              precision    recall  f1-score   support

          -1       0.67      0.78      0.72        60
           1       0.89      0.83      0.86       132

   micro avg       0.81      0.81      0.81       192
   macro avg       0.78      0.80      0.79       192
weighted avg       0.82      0.81      0.82       192



In [47]:
gradentcv(dfComp)

[[ 38  17]
 [ 24 113]]
              precision    recall  f1-score   support

          -1       0.61      0.69      0.65        55
           1       0.87      0.82      0.85       137

   micro avg       0.79      0.79      0.79       192
   macro avg       0.74      0.76      0.75       192
weighted avg       0.80      0.79      0.79       192

[[ 28  27]
 [ 16 121]]
              precision    recall  f1-score   support

          -1       0.64      0.51      0.57        55
           1       0.82      0.88      0.85       137

   micro avg       0.78      0.78      0.78       192
   macro avg       0.73      0.70      0.71       192
weighted avg       0.77      0.78      0.77       192

[[ 31  24]
 [  4 133]]
              precision    recall  f1-score   support

          -1       0.89      0.56      0.69        55
           1       0.85      0.97      0.90       137

   micro avg       0.85      0.85      0.85       192
   macro avg       0.87      0.77      0.80       192
weigh

## Comp

In [ ]:
PCA(dfComp)

In [ ]:
tsne(dfComp)

In [ ]:
knn(dfComp)

In [ ]:
corrMat(dfComp)

In [ ]:
gradent(dfComp)

## Redes

In [ ]:
PCA(dfRedes)

In [ ]:
tsne(dfRedes)

In [ ]:
knn(dfRedes)

In [ ]:
corrMat(dfRedes)

## Mec

In [ ]:
PCA(dfMec)

In [ ]:
tsne(dfMec)

In [ ]:
knn(dfMec)

In [ ]:
corrMat(dfMec)

# CIC

In [ ]:
PCA(dfCic)

In [ ]:
tsne(dfCic)

In [ ]:
knn(dfCic)

In [ ]:
corrMat(dfCic)

# Eng

In [ ]:
PCA(dfEng)

In [ ]:
tsne(dfEng)

In [ ]:
knn(dfEng)

In [ ]:
corrMat(dfEng)